version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    update-types:
      - "minor"
      - "patch"
      - "major"
    labels:
      - "dependencies"
