version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:01"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:02"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    labels:
      - "github-actions"
      - "dependencies"
