version = 1

exclude_patterns = [
  "node_modules/**",
  ".next/**", 
  "out/**",
  "build/**",
  "dist/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  skip_doc_coverage = ["module", "class", "function"]

[[transformers]]
name = "javascript"
