version = 1

exclude_patterns = [
  "node_modules/**",
  ".next/**", 
  "out/**",
  "build/**",
  "dist/**",
  "*.min.js",
  "*.d.ts",
  "next-env.d.ts",
  "tsconfig.tsbuildinfo"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs", "browser"]
  skip_doc_coverage = true
  
  [analyzers.ignore_rules]
  # Ignore documentation requirements
  - "JS-D1001"  # Documentation comments not found for functions and classes
