name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{github.actor == 'dependabot[bot]'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Add a label for all PR
        run: gh pr edit "$PR_URL" --add-label "@rodcast"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
